"""Migration runbook and executive summary generation."""

from __future__ import annotations

from morphsql.models import MigrationReport
from morphsql.risk.scorer import recommend_workload_action


def generate_runbook(report: MigrationReport) -> str:
    """Generate a markdown migration runbook from a scan report."""
    d = report.dashboard
    src = report.source_dialect.value.upper()
    tgt = report.target_dialect.value.upper()

    lines = [
        f"# Migration Runbook",
        f"",
        f"**Source:** {src} · **Target:** {tgt} · **Repository:** `{report.repository_path}`",
        f"",
        f"## Executive summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Objects discovered | {d.total_objects} |",
        f"| Auto-migratable | {d.auto_migratable} |",
        f"| Requires review | {d.requires_review} |",
        f"| Manual redesign | {d.requires_redesign} |",
        f"| Retire / consolidate | {d.recommended_retirement} |",
        f"| Migration risk score | {d.migration_risk_score:.0f} / 100 |",
        f"| Lineage coverage | {d.lineage_coverage_pct:.0f}% |",
        f"| Validation pass rate | {d.validation_passed_pct:.0f}% |",
        f"| Est. annual savings | ${d.estimated_annual_savings_usd[0]:,.0f} – ${d.estimated_annual_savings_usd[1]:,.0f} |",
        f"",
        f"## Recommended phases",
        f"",
        f"### Phase 1 — Discovery (complete)",
        f"- Scanned {d.total_objects} objects",
        f"- Built dependency lineage ({d.lineage_coverage_pct:.0f}% coverage)",
        f"- Identified {d.recommended_retirement} retirement candidates",
        f"",
        f"### Phase 2 — Low-risk conversion",
        f"- Migrate {d.auto_migratable} automatically migratable objects",
        f"- Generate dbt staging/intermediate/mart structure",
        f"- Run reconciliation tests (row count, null rate, checksums)",
        f"",
        f"### Phase 3 — Review queue",
        f"- Engineering review for {d.requires_review} objects",
        f"- Address behavior warnings ({len(report.behavior_warnings)} detected)",
        f"",
        f"### Phase 4 — Redesign",
        f"- Manual redesign for {d.requires_redesign} high-complexity objects",
        f"- Decompose stored procedures into modular pipelines",
        f"",
        f"### Phase 5 — Cutover",
        f"- Parallel run source vs target",
        f"- Validate business metrics within tolerance",
        f"- Retire legacy platform after sign-off",
        f"",
        f"## Object action plan",
        f"",
        f"| Object | Type | Action | Complexity | Risk |",
        f"|--------|------|--------|------------|------|",
    ]

    for obj in sorted(report.objects, key=lambda o: o.complexity_score, reverse=True):
        action = recommend_workload_action(obj).replace("_", " ")
        lines.append(
            f"| {obj.name} | {obj.object_type.value} | {action} "
            f"| {obj.complexity_score} | {obj.risk_level.value} |"
        )

    if report.behavior_warnings:
        lines += ["", "## Platform behavior risks", ""]
        for w in report.behavior_warnings:
            lines.append(f"- {w}")

    if report.retirement_candidates:
        lines += ["", "## Retirement candidates", ""]
        for r in report.retirement_candidates:
            lines.append(f"- {r}")

    lines += [
        "",
        "## Validation checklist",
        "",
        "- [ ] Row count reconciliation per object",
        "- [ ] Null rate comparison on string columns",
        "- [ ] Aggregate metric tolerance (financial columns)",
        "- [ ] Incremental load replay test",
        "- [ ] Procedure parameter binding verified",
        "- [ ] dbt schema tests generated and passing",
        "",
        "---",
        "*Generated by MorphSQL*",
    ]

    return "\n".join(lines)


def generate_executive_summary(report: MigrationReport) -> str:
    """Short executive summary for dashboard display."""
    d = report.dashboard
    savings = d.estimated_annual_savings_usd
    return (
        f"Scanned **{d.total_objects} objects** from `{report.repository_path}`. "
        f"**{d.auto_migratable}** are ready for automatic migration; "
        f"**{d.requires_review}** need engineering review; "
        f"**{d.requires_redesign}** require redesign. "
        f"Average risk score **{d.migration_risk_score:.0f}/100**. "
        f"Estimated annual savings **${savings[0]:,.0f}–${savings[1]:,.0f}** "
        f"after moving from {report.source_dialect.value.upper()} to "
        f"{report.target_dialect.value.upper()}."
    )
